services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: gate_ai_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gate_ai
    ports:
      - "5433:5432"
    volumes:
      - gate_ai_pgdata:/var/lib/postgresql/data

volumes:
  gate_ai_pgdata:
